#!/bin/bash
set -ex

export PIP_INDEX_URL=https://pypi.org/simple/
export PIP_TRUSTED_HOST="pypi.org files.pythonhosted.org"

echo $DB_CLUSTER_NAME

URL=https://raw.githubusercontent.com/Defra-Data-Science-Centre-of-Excellence/esd-init-scripts/main/src

wget $URL/rootcerts.sh -O- | bash
wget $URL/update.sh -O- | bash 
wget $URL/c_dependencies.sh -O- | bash 
wget $URL/sedona_172.sh -O- | bash 

# installed through the libraries GUI instead as programatically didn't work
#pip install /Volumes/prd_dash_lab/esa_restricted/sds/sds_dash_download-0.1.0-py3-none-any.whl

# other libraries
pip install pyogrio==0.11.0
pip install pandana==0.7
pip install shapely==2.1.0
pip install matplotlib==3.8.3
pip install mapclassify==2.6.1
pip install folium==0.15.1
pip install rioxarray==0.18.2
pip install pandera[geopandas]==0.31
pip install dask-geopandas==0.5.0
pip install numba==0.63.1
pip install --upgrade --force-reinstall pydantic==2.11